### ISSUE TITLE
Définir ce qu'il se passe si un membre ne respecte pas le code de conduite

### ISSUE THREAD

**Issue by BodySplash** [ordre-des-developpeurs/odd-constitution#4]
Éviction ? De quelle manière pour éviter les abus ? Tirage au sort d'un juris ?

**Comment by jermorin** [comment]
Je reste un peu dubitatif devant ce rôle de sanction.

En effet, comment l’ordre peut-il assurer un rôle de soutien, de conseil et de sanction.

Le métier de développeur demande une évolution permanente, on apprend des erreurs, on tente de sortir constamment de nos zones de confort, pour aller plus loin et plus haut dans la compétence et l’organisation. 

Mais cela à un prix, malgré notre «professionnalisme» et notre envie de bien faire, nous pouvons nous tromper (et peut être sortir de la bonne conduite). Normalement, dans notre métier l’erreur on ne l’a reproduira pas deux fois. Mais quand on comprend que c’est une erreur, elle est déjà commise. 

L’ordre est là pour soutenir les développeurs, on peut discuter de nos erreurs pour apprendre comment ne plus les reproduire, mais l’ordre peut aussi les sanctionner. La barrière est fine. 

Et si la sanction intervenait : 
- Que si la faute était cachée ? (faute avouée à moitié pardonnée) 
- Que si le développeur est juste contre le fait de s’améliorer ?

À mon sens, l’ordre doit être une épaule avant une police, le vote d’une éventuelle radiation de l’ordre est contre le principe de communication et de partage (et ressemble trop à un jugement).

Cependant, je suis conscient que si l’ordre ce rempli de développeurs «peu scrupuleux» il ne sera plus gage d’une éthique.

Puis en y réfléchissant, un développeur qui va commettre des fautes de conduites à répétition, ne se retirait-il pas seul, en comprenant qu’il a plus grand-chose en commun avec le groupe ? Je ne suis même pas sûr qu’il l’intégrerait ?

**Comment by kryzaal** [comment]
Sans rôle judiciaire interne, autant fermer boutique tout de suite.
Il y aura forcément des règles décidées par les développeurs et donc des juges désignés pour les faire respecter.

**Comment by Squallygator** [comment]
Si chaque membre avais une fiche signalétique de là ou il se situe où il indiquerai a quel niveau il se situe/pretend (checklist) par rapports à la charte du développeur (ou code de conduite).
Pourquoi ne pas envisager aussi un principe du casier judiciaire ? 

> Faute avouée à moitié pardonnée.

A chacun de se faire son idée sur le bien fondé de sa présence dans l'ordre.

_Exemple_:

**Todo**
...
- [x] Le devoir de rendre publique les concessions faites a cette charte sur un projet.
- [ ] Le devoir de s'améliorer
  - [ ] Nous ne pouvons pas faire payer à un projet notre envie d'apprendre une nouvelle technologie à nos clients. 
  - [ ] Nous ne pouvons proposer que des options que nous connaissons, ou bien être très clair sur nos limites.

**Fails !**
- 4/11/2015
  - à fait payé a sa boite le coût d'apprentissage d'un nouvelle techno sans justification ni négociation. 

Bonne ou mauvaise idée ?

**Comment by BodySplash** [comment]
L'idée effectivement est de tenter de se séparer des développeurs peu scrupuleux. Il y a une différence entre faire des erreurs dues à un manque d'appréciation, ou de connaissance sur un sujet donné, et sempiternellement stagner, considérer que les bugs, c'est la responsabilité des testeurs, voir en introduire à dessein pour mieux facturer leur correction. 

Dans un premier temps effectivement, pas besoin de beaucoup cogiter. Fondamentalement, l'ordre va attirer des personnes en accord avec la philosophie. En cas de succès, ou ne pas faire partie de l'ordre pourrait être préjudiciable pour sa carrière, alors là, il faudra je pense mettre en place ce mécanisme de détection des accaparions purement commerciales. Je ne me prononce pas encore en tout cas sur de telles mécanismes :)

**Comment by josselinauguste** [comment]
L'évaluation par les pairs est surement le système le plus neutre et le plus objectif.

**Comment by abelards** [comment]
Ça me rappelle tous les débats sur les Code of Conduct.

C'est plutôt simple : être développeur, développer, et faire partie de l'Ordre sont des choses différentes.
Vous n'allez jamais pouvoir interdire le code à quelqu'un [1], et d'ailleurs en ne voulant pas certifier vous ne pouvez rien faire non plus : la black-list des "méchants" ? la white-list des "gentils développeurs" ?

Mais vous pouvez dans le périmètre restreint dire "nous ne voulons plus que tu participes à l'Ordre (car tu participes de manière toxique) ni que tu portes notre image (car ça ne nous correspond pas/plus)".


[1] "tu as codé la triche VolksWagen, tu es interdit de faire du C++" ?
"ta lib de traitement d'image a permis d'emprisonner des opposants à une dictature grâce à la reconnaissance faciale sur les vidéo surveillance de la Place Machin, tu es révoqué de l'Ordre" ?

**Comment by BodySplash** [comment]
Le but n'est pas tant d'interdire de coder, c'est impossible et très douteux. Ma vision maintenant est un petit peu comme les compagnons du tour de france : tu as pas besoin d'en être pour exercer ton métier; maintenant si des clients préfèrent se tourner vers cette structure pour y trouver un certain niveau de garanti, alors c'est plutôt pas mal. Bien sûr, dans ce genre de métaphore, je me méfie beaucoup du côté certifiant de la chose.

**Comment by abelards** [comment]
Si l'Ordre sert de proxy pour mettre en relation clients et prestas,
tu vas finir par avoir tous les problèmes de business que tu redoutais.

**Comment by BodySplash** [comment]
Tout à fait, toute cette question est très épineuse. Naïvement je me disais que l'ordre ne serait pas un proxy. Un client n'appelle pas l'ordre pour avoir un presta. Un client peut aller voir un éventuel annuaire. Ceci dit, ça ne marche pas complètement. Dans une situation improbable ou être membre de l'ordre est devenu une sorte de condition tacite du marché pour être embauchable, alors la pression à participer détruit tout l'intérêt de la chose.

**Comment by esandre** [comment]
Improbable, improbable ... L'histoire montre qu'un ordre qui marche finit de fait en quasi-monopole
